// SPDX-FileCopyrightText: 2026 OpenCHAMI Contributors
//
// SPDX-License-Identifier: MIT

package main

import (
	"go/format"
	"strings"
	"testing"
)

func TestRegistrationGeneratorsIncludeGeneratedSPDXHeader(t *testing.T) {
	oldVersion := version
	version = "test-version"
	defer func() {
		version = oldVersion
	}()

	apisConfig := DefaultAPIsConfig("example.fabrica.dev", "v1", []string{"v1"})

	for name, content := range map[string]string{
		"non-versioned": generateRegistrationCode("example.com/test", []string{"Device"}),
		"versioned":     generateVersionedRegistrationCode("example.com/test", apisConfig, []string{"Device"}),
	} {
		if !strings.Contains(content, "Code generated by Fabrica test-version. DO NOT EDIT.") {
			t.Fatalf("%s registration missing generated banner", name)
		}
		if !strings.Contains(content, "Copyright © ") {
			t.Fatalf("%s registration missing copyright header", name)
		}
		// If the line below includes a full header, it will flag the reuse test as a malformed header and fail.
		if !strings.Contains(content, "PDX-License-Identifier: MIT") {
			t.Fatalf("%s registration missing SPDX license header", name)
		}
	}
}

func TestRegistrationGeneratorsProduceGofmtStableOutput(t *testing.T) {
	apisConfig := DefaultAPIsConfig("example.fabrica.dev", "v1", []string{"v1"})

	for name, content := range map[string]string{
		"non-versioned": generateRegistrationCode("github.com/openchami/boot-service", []string{"Node", "BMC"}),
		"versioned":     generateVersionedRegistrationCode("github.com/openchami/boot-service", apisConfig, []string{"Node", "BMC"}),
	} {
		_, err := format.Source([]byte(content))
		if err != nil {
			t.Fatalf("%s registration should be gofmt-able: %v", name, err)
		}
	}
}
